language: node_js
node_js:
  - "16"
os: linux
dist: xenial

before_script:
  - npm install -g browserify
  - npm install @codemirror/basic-setup
  - npm install @codemirror/lang-javascript
  
script:
  - browserify main.js -o bundle.js
#  - ls -l

deploy:
  provider: releases
  token: $GITHUB_API_KEY
  skip_cleanup: true
  file: $TRAVIS_BUILD_DIR/bundle.js
  name: dev-build-$TRAVIS_TAG
  release_notes: Automatic build of $TRAVIS_BRANCH ($TRAVIS_COMMIT) built by Travis CI on $(date +'%F %T %Z').
  prerelease: true
  overwrite: true
  target_commitish: $TRAVIS_COMMIT
  on:
    tags: true

after_deploy:
  - rm -rf $TRAVIS_BUILD_DIR/bundle.js
