name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  Build:
    runs-on: '${{ matrix.os }}'
    strategy:
      matrix:
        os:
          - ubuntu-latest
        node-version:
          - 16
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: 'Set up Node.js ${{ matrix.node-version }}'
        uses: actions/setup-node@v2
        with:
          node-version: '${{ matrix.node-version }}'
      - name: Generate Bundle
        run: |
          npm i -g rollup
          npm i @rollup/plugin-node-resolve
          npm i @codemirror/basic-setup
          npm i @codemirror/lang-javascript
          npm i @codemirror/theme-one-dark
          rollup -c
      - name: Archive artifact
        uses: actions/upload-artifact@v2
        with:
          name: bundle
          path: bundle.js
