name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  Build:
    runs-on: '${{ matrix.os }}'
    strategy:
      matrix:
        os:
          - ubuntu-latest
        node-version:
          - 16
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '${{ matrix.node-version }}'
      - run: npm install -g browserify
      - run: npm install browser-resolve
      - run: npm install esmify
      - run: npm install @codemirror/basic-setup
      - run: npm install @codemirror/lang-javascript
      - run: npm install @codemirror/theme-one-dark
      - run: browserify main.js -p esmify > bundle.js
